name: mangabuzz
description: Aplikasi baca manga bahasa Indonesia

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  bloc: ^6.0.3
  flutter_bloc: ^6.0.5
  http: ^0.12.2
  dartz: ^0.9.1
  connectivity: ^0.4.9+5
  equatable: ^1.2.5
  moor: ^3.3.1
  sqlite3_flutter_libs: ^0.2.0
  path: ^1.7.0
  path_provider: ^1.6.14
  moor_flutter:
  flutter_cache_manager: ^2.0.0
  cached_network_image: ^2.3.3
  moor_ffi: ^0.8.0
  flutter_screenutil: ^3.1.1
  carousel_slider: ^2.2.1
  smooth_page_indicator: ^0.2.0
  google_nav_bar: ^3.0.1
  line_icons: ^0.2.0
  content_placeholder: ^0.1.0
  flutter_rating_bar: ^3.0.1+1
  flutter_animation_progress_bar: ^1.0.5
  flutter_dropdown: ^0.0.8
  readmore: ^1.0.0
  draggable_scrollbar: ^0.0.4
  permission_handler: ^5.0.1+1
  url_launcher: ^5.7.5
  cool_alert: ^1.0.1
  shared_preferences: ^0.5.12
  auto_size_text: ^2.1.0
  flutter_slidable: ^0.5.7
  get_it: ^5.0.1
  easy_localization: ^2.3.3
  easy_localization_loader: ^0.0.2
  flutter_localizations:
    sdk: flutter

dependency_overrides:
  image: ^2.1.18
  xml: ^4.5.1
  flutter_svg: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.2
  mockito: ^4.1.1
  build_runner: ^1.10.1
  moor_generator: ^3.3.1
  build_resolvers: ^1.3.10
  flutter_launcher_icons: ^0.8.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "resources/img/icons.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - resources/img/
    - resources/langs/langs.csv

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: resources/fonts/Poppins-Regular.ttf
    - family: Poppins-Medium
      fonts:
        - asset: resources/fonts/Poppins-Medium.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: resources/fonts/Poppins-SemiBold.ttf
    - family: Poppins-Bold
      fonts:
        - asset: resources/fonts/Poppins-Bold.ttf
    - family: Poppins-ExtraBold
      fonts:
        - asset: resources/fonts/Poppins-ExtraBold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
